export const inputs =[
    {
      id:1,
      name:"firstName",
      type:"text",
      placeholder:"FirstName",
      errorMessage:"Username should be 3-16 characters and shouldn't include any special character!",
      label:"FirstName",
    },
    {
      id:2,
      name:"lastName",
      type:"text",
      placeholder:"LastName",
      errorMessage:"Username should be 3-16 characters and shouldn't include any special character!",
      label:"LastName",
    },
    {
      id:3,
      name:"username",
      type:"text",
      placeholder:"Username",
      errorMessage:"Username should be 3-16 characters and shouldn't include any special character!",
      label:"Username",
      pattern:"^[A-Za-z0-9]{3,16}",
      required:true,
    },
    {
      id:4,
      name:"email",
      type:"email",
      placeholder:"Email",
      errorMessage:"It should be a valid email address!",
      label:"Email",
     
      required:true,
    },
    {
      id:5,
      name:"password",
      type:"password",
      placeholder:"Password",
      errorMessage:"Password should be 8-20 characters and include at least 1 letter, 1 number and 1 special character!",
      label:"Password",
      required:true,
    },
    {
      id:6,
      name:"confirmPassword",
      type:"password",
      placeholder:"Confirm Password",
      errorMessage:"Passwords don't match!",
      label:"Confirm Password",
      pattern:values.password,
      required:true,
    },
  ]